-- ============================================================
-- Bu dosyadaki tüm içerikler ilgili dosyalara taşındı:
--
--   schema.sql    → tablo kolonları, indexler, replica identity
--   functions.sql → nearby_projects fonksiyonu
--   policies.sql  → badges RLS policy'leri
--
-- Bu dosya artık kullanılmamaktadır.
-- ============================================================
